name: Publish Mullvad PAC scripts

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  schedule:
    - cron: 11 */8 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set build information
      id: info
      run: |
        echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Install python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Clone the scripts branch
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: scripts
        path: scripts

    - name: Remove previously created scripts
      run: |
        cd scripts
        rm *.pac || true

    - name: Create new PAC scripts
      run: |
        python3 create-pac-scripts.py

    - name: Push result to scripts branch
      run: |
        cd scripts
        git add .
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git diff --cached --exit-code &> /dev/null || echo Committing
        git diff --cached --exit-code &> /dev/null || git commit -am "${{ steps.info.outputs.date }}"
        git diff --exit-code origin/scripts &> /dev/null || echo Pushing
        git diff --exit-code origin/scripts &> /dev/null || git push -u origin scripts
